### ISSUE TITLE
Having no SDF3 files in the main source directory results in compilation issues in generated files

### ISSUE THREAD

**Issue by molenzwiebel** [metaborg/spoofax-pie#112]
Assume the following file structure:

```
src/
  syntax/
    lang/
      a.sdf3
      b.sdf3
      main.sdf3
```

and the following `spoofaxc.cfg`:

```
sdf3 {
  source = files {
    main-source-directory = ./src/syntax
    main-file = ./lang/main.sdf3
  }
}
```

Signatures will be generated in `signatures/lang/a.str2`, etc. Injections will be generated in `injections/lang/a.str2`, etc.

However, certain files contain wildcard imports to `signatures/-` and `injections/-`, which results in compilation errors because wildcard imports are not recursive and no files exist directly inside the signature/injections directories.

One of such files is unarchived from libstatix:

```
Messages of ./build/unarchive/libstatix.eclipse-999.9.9-develop-SNAPSHOT.jar/mb/libstatix/trans/statix/runtime/renaming.str2:
  ERROR 62-74@5-6: Cannot find module for import 'signatures'
```

Since this file is generated by the build process, the only workaround is to ensure that at least one file exists in the `signatures` folder (and ideally one that in turn imports all other files). 

## Context

* Spoofax version: devenv with spoofax-pie metaborg/spoofax-pie@389964a5

**Comment by Gohla** [comment]
Hmm, this might just be an issue in the way we archive/unarchive `libstatix`. It imports `signatures` because the project has SDF3 files that get converted to Stratego signatures. Maybe those are not available, not passed as an include to the Stratego compiler, or there is a conflict with multiple `signatures` directories and the one in the language gets picked and thus fails?

**Comment by Gohla** [comment]
Should be fixed by https://github.com/metaborg/nabl/pull/101 (which was also pulled into the `spoofax3` branch)
