### ISSUE TITLE
Generation/analysis loop when opening a Statix signature file in Eclipse

### ISSUE THREAD

**Issue by molenzwiebel** [metaborg/spoofax-pie#30]
When opening a statix signature file in Eclipse, some task seems to run that ends up writing an identical signature file to disk. This will then cause Eclipse to reload the file, which in turn triggers another analysis, which will write a file, etc.

I haven't looked to deeply into what causes this, but I suspect either moving to a hash resource stamper or preventing the writing of an indentical file would be a simple way to fix this. 

This issue is slightly higher priority now that we have go-to-definition support in Statix, since that means that it becomes more likely for the user to actually open the generated files in their Eclipse instance.

**Comment by Gohla** [comment]
This should be fixed by https://github.com/metaborg/spoofax-pie/commit/85bd458e106399126c1b56168ad824847ecbe8f4.
