### ISSUE TITLE
SDF3: Error in import causes a cascade of unrelated errors in the file

### ISSUE THREAD

**Issue by Virtlink** [metaborg/spoofax-pie#33]
## Summary
In SDF3, an error in an import causes a cascase of unrelated errors in the file.

## What you did
An existing SDF3 file had a broken import. I imported `Common` (upper case) from `Common.sdf3`, but the module in `Common.sdf3` was named `module common` (lower case).

```
imports Common
```

## What you expected to happen
I expected only an error on the import and maybe errors on the undefined sorts.

## What actually happened
I got errors on all the constructors and sorts.

## Context
* Spoofax version: Spoofax 3 v0.11.0
* Operating system & version: macOS 11.5.2
* Java version: AdoptOpenJDK-11.0.11+9
* Eclipse version: 2021-03 (4.19.0) build 20210312-0638
* Gradle version: Gradle 6.8

## Additional information
<img width="1022" alt="Screenshot 2021-09-07 at 13 42 34" src="https://user-images.githubusercontent.com/647530/132338939-fbca22f7-4f36-422c-8762-7015d772e6a6.png">

**Comment by Gohla** [comment]
Hmm, could these be cascading errors due to the SDF3 Statix spec? I am not sure how to fix that

**Comment by Gohla** [comment]
This will be improved in the next release due to improved cascaded error handling in the Statix solver.
