### ISSUE TITLE
Starting Eclipse with embedded JVM on Linux fails

### ISSUE THREAD

**Issue by Gohla** [metaborg/spoofax-pie#37]
## Summary
Starting Eclipse with embedded JVM on Linux fails with a long and confusing error. This is due to the `java` executable not having executable permission, probably due to that bit not being copied when unarchiving the JVM when creating the installer, or that bit not being copied into the new archive.

## What you did
Start Eclipse with embedded JVM on Linux.

## What you expected to happen
Eclipse to start.

## What actually happened
A long and confusing error popup appears.

## Context
* Spoofax version: 0.11.6
* Operating system & version: Linux

**Comment by Konpon96** [comment]
Can confirm that the issue persists in Spoofax 0.11.7 Eclipse distribution.

**Comment by Gohla** [comment]
Hopefully fixed by https://github.com/metaborg/coronium/commit/1a0527fb6052901c1f5cdaf89758afc19ad375de, but testing on Linux will be needed to confirm this.
