### ISSUE TITLE
SDF3 file cannot be named main.sdf3

### ISSUE THREAD

**Issue by Virtlink** [metaborg/spoofax-pie#43]
## Summary
An sdf3 file cannot be named `main.sdf3`.

## What you did
As all the main files in a Spoofax 3 project are named `main`, I renamed `start.sdf3` to `main.sdf3` (and changed the module name). This, however, failed because the build could no longer locate `src/start.sdf3`. Then I thought I would add a dummy `start.sdf3` that redirects to main, but then I get errors that `main` cannot be found (even after clean). Renaming `main.sdf3` to `main2.sdf3` (and changing the module name) fixed the issue.

```
module start
imports main
```

## What you expected to happen
I expected `main.sdf3` to be fine.

## What actually happened
The `main` SDF3 module could not be found, whereas renaming it to `main2` fixed the issue.

## Context
* Spoofax version: Spoofax 3 v0.11.0
* Operating system & version: macOS 11.5.2
* Java version: AdoptOpenJDK-11.0.11+9
* Eclipse version: 2021-03 (4.19.0) build 20210312-0638
* Gradle version: Gradle 6.8

**Comment by Gohla** [comment]
That is a limitation of SDF3, which is why it is named start. If it is fixed in SDF3, then it will work here as well.
