### ISSUE TITLE
SPT errors stick around in Eclipse after a rebuild

### ISSUE THREAD

**Issue by molenzwiebel** [metaborg/spoofax-pie#50]
## Summary
If an SPT editor is open and has errors, those errors may persist even if a rebuild is done that will cause those tests to succeed. Editing or reopening the SPT file will then cause those errors to recompute (and disappear).

## What you did
- Write a test that fails
- Open the SPT file in Eclipse such that the error marker shows up for that test
- Change the grammar to allow the test to succeed
- Trigger a build, compiling the grammar
- Error marker still shows in SPT editor until it is reopened or the contents are changed

## What you expected to happen
Errors/error markers are automatically updated.

## What actually happened
Old results persist.

## Context

* Spoofax version: 0.11.9
* Operating system & version: all

**Comment by Gohla** [comment]
Hmm, that should not happen. Does this happen without a clean? If a clean is done, then the SPT editor check is no longer observed and thus it is no longer updated.
