### ISSUE TITLE
SDF3 constructor name reuse across different sorts results in errors in the Statix signature

### ISSUE THREAD

**Issue by molenzwiebel** [metaborg/spoofax-pie#51]
## Summary
Using the same constructor name across different sorts results in errors in the generated Statix signatures (and possibly other things).

## What you did

```
  Start.Program = Exp* Stmt*
  
  Stmt.Aa = <<ID>>
  Exp.Aa = <<INT>>
```

## What you expected to happen

Error that `Aa` is duplicated across `Stmt` and `Exp`.

## What actually happened

```
Messages of ./build/generated/sources/languageSpecification/statix/signatures/start-sig.stx:
ERROR 333-335@25: Duplicate constructor "Aa/1"
ERROR 294-296@23: Duplicate constructor "Aa/1"
```

## Context

* Spoofax version: 0.11.9
* Operating system & version: all

## Additional information

This may also cause issues in other parts. Spoofax 2 normally emits a warning here, talking about the generated pretty printer.

**Comment by Gohla** [comment]
Fixed by https://github.com/metaborg/sdf/commit/e01c3d0ed3ad41addb6888f31dd293adf6e1a8c0, to be released in the next release.
