### ISSUE TITLE
SDF3 constructors that start with a lowercase letter cause errors in the generated Statix signature

### ISSUE THREAD

**Issue by molenzwiebel** [metaborg/spoofax-pie#52]
## Summary
Starting a constructor with a lower-case letter results in invalid syntax for the generated Statix signature.

## What you did

```
Start.aa = <1>
```

## What you expected to happen

Works.

## What actually happened

```
Messages of ./build/generated/sources/languageSpecification/statix/signatures/start-sig.stx:
ERROR 292-295@23: Syntax error, expected: 'imports'
ERROR 296-302@24: Syntax error, not expected here: '    aa'
ERROR 303-304@24: Syntax error, not expected here: ':'
ERROR 310@24: Syntax error, expected: 'constructors'
ERROR ...
```

## Context

* Spoofax version: 0.11.9
* Operating system & version: all

**Comment by Gohla** [comment]
Fixed by https://github.com/metaborg/sdf/commit/b3054160637e83802f3a5ec0a526370158f9075f, to be released in the next release.
