### ISSUE TITLE
Support for Statix tests

### ISSUE THREAD

**Issue by AZWN** [metaborg/spoofax-pie#62]
Supporting Statix tests greatly helps debugging Statix specifications, and would therefore be a nice feature to support in Spoofax 3.

Support can be added when the following steps are implemented:
- In the Statix language, add a menu option "Evaluate test" that executes the `evaluate-test :: AST -> TestResult` strategy, available in `statix.lang`. This strategy takes the test AST as input, and returns a test result.
- The test result can be pretty-printed with the `pp-Statix-string(prettyprint-Statix-TestResult)` strategy. The resulting string should be opened in a file with (preferably) an `.stxresult` extension.

For reference, the definition of this menu in Spoofax 2 can be found [here](https://github.com/metaborg/nabl/blob/c1955a2e01709871d006a78842237857a5c69a11/statix.lang/trans/statix/test/evaluate.str#L27-L30).

**Comment by Gohla** [comment]
@AZWN is the extension for those kind of files `.stxtest`, and are those valid Statix files (i.e., parseable by `statix.lang`)? And is the output also valid Statix?

**Comment by AZWN** [comment]
> is the extension for those kind of files .stxtest

Yes

> and are those valid Statix files

Yes

> And is the output also valid Statix?

The output of the evaluation strategy can be pretty-printed as Statix, but is not parsable. Also, the `stxresult` extension is not recognized as a Statix file extension. There have been plans to make these files parsable, but there is no implementation of that yet.

**Comment by Gohla** [comment]
Implemented as part of https://github.com/metaborg/spoofax-pie/commit/62ea9a40e1375d097ba256032a88cb9a5010e48a and https://github.com/metaborg/nabl/commit/aeb8d095583a1d8659618baba7fd0cec4e9c774d, to be released in the next release.
