### ISSUE TITLE
SPT parse to ATerm constructor names don't support underscores

### ISSUE THREAD

**Issue by RvanBaarle** [metaborg/spoofax-pie#67]
## Summary
Constructor names containing underscores aren't parsed correctly in SPT files.

## What you did
Defining a constructor such as
```
Start.Hello_World = <Hello world>
```
And a test such a
```
test hello [[
Hello world
]] parse to Hello_World()
```

## What you expected to happen
The test should pass

## What actually happened
The test fails with the error "Expected parse to (), but got Hello_World()"

## Context
* Spoofax version: devenv (spoofax.pie commit c7ed510dd0f4b6a59f3e6134cf574d41e4cf7e51)
* Operating system & version: Ubuntu 20.04
* Java version (if applicable): 11.0.11
* Eclipse version (if applicable): Version: 2021-03 (4.19) Build id: I20210303-1800
* Gradle version (if applicable): 6.8

## Additional information
The SPT file does evaluate, but "Show parsed AST" does not produce an AST.

**Comment by Gohla** [comment]
Solved by https://github.com/metaborg/spt/commit/a5253d11bd05825d1e2bbdf7b241ac1e21aab741
