### ISSUE TITLE
Statix: support for traces and term depth configuration

### ISSUE THREAD

**Issue by AZWN** [metaborg/spoofax-pie#75]
In order to debug Statix specifications, it would be useful to be able to control the stack trace length and the term depth of the messages that are generated.

**Comment by Gohla** [comment]
@AZWN In Spoofax 2, this is configurable per-project right? We do not yet have project-specific settings in Spoofax 3, and this is something that I want to spend some design time on to get it right in Spoofax 3. Would it be fine for now to have this configurable per-language, and overridable per-project in the future? And what do you think the defaults should be?

**Comment by AZWN** [comment]
Yes, a per-language solution would be fine for now. The Spoofax 2 defaults are: 0 for stack trace length, and 3 for term depth.

**Comment by Gohla** [comment]
Implemented in https://github.com/metaborg/spoofax-pie/commit/21fc3f3a1d6687fac8361bce6d3a1b901cf65970
