### ISSUE TITLE
LAYOUT?-CF not accepted in Sdf3 Statix

### ISSUE THREAD

**Issue by Virtlink** [metaborg/spoofax-pie#78]
The Statix specification correctly rejects any optional sorts (`A?`) in context-free syntax. However, the `LAYOUT?` sort is special in kernel syntax, and I think it should be allowed:

```sdf3
Section-CF.Section = "section" SectionName-CF LAYOUT?-CF Definition*-CF
```

> Optionals (A?) are not allowed in context-free syntax

Here is a project with WebDSL syntax in which this is an issue, in `WebDSL-Core.sdf3`, line 49:

:open_file_folder: [webdsl.zip](https://github.com/metaborg/spoofax-pie/files/7293212/webdsl.zip)

**Comment by Gohla** [comment]
There seems to be a bug where the SDF3->Stratego signature generator fails on `LAYOUT?-CF` in those kernel syntax productions, I will have a look at that tomorrow.

**Comment by Gohla** [comment]
Should be fixed https://github.com/metaborg/sdf/commit/d88c75aa1f83c8c16e8e1ce88cd9036bb3787473 (untested)
