### ISSUE TITLE
NullPointerException when editing files

### ISSUE THREAD

**Issue by wandersiemers** [metaborg/spoofax-pie#81]
## Summary

The spoofax editor crashes when I make changes to a .spt test file, giving a NullPointerException on every keystroke. 
## What you did

Open a .spt file, make some changes, wait until the editor reloads and immediately crashes with 'SPT Editor Update'. 
## What you expected to happen

Editor updates and reruns tests

## What actually happened

Editor crashes 

## Context

* Spoofax version: 0.14.2
* Operating system & version: MacOS 11.6
* Java version (if applicable): embedded JVM
* Eclipse version (if applicable): 2021-03
* Gradle version (if applicable):

## Additional information
Log of SPT Editor Update:
[error-log.txt](https://github.com/metaborg/spoofax-pie/files/7402732/error-log.txt)

**Comment by Gohla** [comment]
If deserialization fails, it defaults to an empty state and will rebuild everything, so that should not be an issue.

**Comment by Gohla** [comment]
I've fixed a bug in 0.15.1 that might cause these `NullPointerException`s, can you try that out?

**Comment by ThijsRay** [comment]
I run into `NullPointerException`s with version 0.15.2 when I open `correctness.spt` ([link to my project on GitLab](https://gitlab.ewi.tudelft.nl/CS4200/2021-2022/student-traijmakers/-/blob/milestone-2-develop/chocopy/test/correctness.spt)). It happens whenever I open, edit or save this file. Previously, I was using version 0.14.2. That version did not have this issue.
